package com.wsy.everylesson.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wsy.everylesson.bean.SearchGreenDao;

import com.wsy.everylesson.db.SearchGreenDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchGreenDaoDaoConfig;

    private final SearchGreenDaoDao searchGreenDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchGreenDaoDaoConfig = daoConfigMap.get(SearchGreenDaoDao.class).clone();
        searchGreenDaoDaoConfig.initIdentityScope(type);

        searchGreenDaoDao = new SearchGreenDaoDao(searchGreenDaoDaoConfig, this);

        registerDao(SearchGreenDao.class, searchGreenDaoDao);
    }
    
    public void clear() {
        searchGreenDaoDaoConfig.clearIdentityScope();
    }

    public SearchGreenDaoDao getSearchGreenDaoDao() {
        return searchGreenDaoDao;
    }

}
