package com.wsy.self_control_view.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wsy.self_control_view.ViewBean;

import com.wsy.self_control_view.db.ViewBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig viewBeanDaoConfig;

    private final ViewBeanDao viewBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        viewBeanDaoConfig = daoConfigMap.get(ViewBeanDao.class).clone();
        viewBeanDaoConfig.initIdentityScope(type);

        viewBeanDao = new ViewBeanDao(viewBeanDaoConfig, this);

        registerDao(ViewBean.class, viewBeanDao);
    }
    
    public void clear() {
        viewBeanDaoConfig.clearIdentityScope();
    }

    public ViewBeanDao getViewBeanDao() {
        return viewBeanDao;
    }

}
