package com.wsy.self_control_view.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.wsy.self_control_view.ViewBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VIEW_BEAN".
*/
public class ViewBeanDao extends AbstractDao<ViewBean, Long> {

    public static final String TABLENAME = "VIEW_BEAN";

    /**
     * Properties of entity ViewBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DateX = new Property(1, float.class, "dateX", false, "DATE_X");
        public final static Property DateY = new Property(2, float.class, "dateY", false, "DATE_Y");
    }


    public ViewBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ViewBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VIEW_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DATE_X\" REAL NOT NULL ," + // 1: dateX
                "\"DATE_Y\" REAL NOT NULL );"); // 2: dateY
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VIEW_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ViewBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindDouble(2, entity.getDateX());
        stmt.bindDouble(3, entity.getDateY());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ViewBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindDouble(2, entity.getDateX());
        stmt.bindDouble(3, entity.getDateY());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ViewBean readEntity(Cursor cursor, int offset) {
        ViewBean entity = new ViewBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getFloat(offset + 1), // dateX
            cursor.getFloat(offset + 2) // dateY
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ViewBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDateX(cursor.getFloat(offset + 1));
        entity.setDateY(cursor.getFloat(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ViewBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ViewBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ViewBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
